name: ZMK firmware
on:
  push:
    paths: ["config/**", "build.yaml", ".github/workflows/zmk-build.yml"]
  workflow_dispatch:
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
